In [2]:
# Importing the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats  #for the statistical tests
from scipy import stats as stats
%matplotlib inline

In [3]:
loans = pd.read_csv(r"C:\Users\bless\OneDrive\Desktop\Data Science\Python\Case Studies\Basic Statistics - Hypothesis Testing\4. Basic Statistics - Hypothesis Testing\LoansData.csv")

In [4]:
loans['Interest.Rate'] = loans['Interest.Rate'].str.replace('%', '', regex=True).astype(float)
loans['Loan.Length'] = loans['Loan.Length'].str.replace(' months', '', regex=True).astype(float)
loans['Debt.To.Income.Ratio'] = loans['Debt.To.Income.Ratio'].str.replace('%', '', regex=True).astype(float)

# a. Intrest rate is varied for different loan amounts (Less intrest charged for high loan amounts)


In [9]:
import pandas as pd
from scipy.stats import ttest_ind

# Divide the loans into two groups based on loan amount
high_loan_amounts = loans[loans['Amount.Requested'] > loans['Amount.Requested'].mean()]
low_loan_amounts = loans[loans['Amount.Requested'] <= loans['Amount.Requested'].mean()]

# Perform a two-sample t-test on the interest rates of the two groups
t_stat, p_val = ttest_ind(high_loan_amounts['Interest.Rate'], low_loan_amounts['Interest.Rate'])

# Print the results of the t-test
print('t-statistic:', t_stat)
print('p-value:', p_val)

t-statistic: 14.147818309512642
p-value: 1.0284924762041011e-43


# 2. Loan length is directly effecting intrest rate

In [11]:
import pandas as pd
from scipy.stats import pearsonr

# Calculate the correlation coefficient between loan length and interest rate
corr_coef, p_val = pearsonr(loans['Loan.Length'], loans['Interest.Rate'])

# Print the results of the correlation test
print('correlation coefficient:', corr_coef)
print('p-value:', p_val)

correlation coefficient: 0.4250573823094828
p-value: 1.7938010673273293e-106


In [10]:
loans['Loan.Purpose'].unique()

array(['debt_consolidation', 'credit_card', 'other', 'moving', 'car',
       'vacation', 'home_improvement', 'house', 'major_purchase',
       'educational', 'medical', 'wedding', 'small_business',
       'renewable_energy'], dtype=object)

# c. Intrest rate varies for different purpose of loans

In [14]:
# Perform the ANOVA test
result = stats.f_oneway(loans[loans['Loan.Purpose'] == 'credit_card']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'debt_consolidation']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'educational']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'major_purchase']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'small_business']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'other']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'moving']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'car']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'home_improvement']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'vacation']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'renewable_energy']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'wedding']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'medical']['Interest.Rate'],
                        loans[loans['Loan.Purpose'] == 'house']['Interest.Rate'])

result

F_onewayResult(statistic=7.33083818591965, pvalue=2.7646672581411367e-14)

# d. There is relationship between FICO scores and Home Ownership. It means that, People with owning home will have high FICO scores.

In [24]:
import pandas as pd
import scipy.stats as stats

# Extract and convert FICO scores from string ranges to integers
loans['FICO.Score'] = loans['FICO.Range'].str.split('-').apply(lambda x: int(x[0]))

# Define the two samples
own_home = loans[loans['Home.Ownership'] == 'OWN']['FICO.Score']
not_own_home = loans[loans['Home.Ownership'] != 'OWN']['FICO.Score']

# Perform the two-sample t-test
result = stats.ttest_ind(own_home, not_own_home)

# Print the results of the test
print(result)

Ttest_indResult(statistic=0.4755690628354589, pvalue=0.6344245033040679)


In [5]:
loans.head()

Amount.Requested  Amount.Funded.By.Investors  Interest.Rate  Loan.Length  \
0           20000.0                     20000.0           8.90         36.0   
1           19200.0                     19200.0          12.12         36.0   
2           35000.0                     35000.0          21.98         60.0   
3           10000.0                      9975.0           9.99         36.0   
4           12000.0                     12000.0          11.71         36.0   

         Loan.Purpose  Debt.To.Income.Ratio State Home.Ownership  \
0  debt_consolidation                 14.90    SC       MORTGAGE   
1  debt_consolidation                 28.36    TX       MORTGAGE   
2  debt_consolidation                 23.81    CA       MORTGAGE   
3  debt_consolidation                 14.30    KS       MORTGAGE   
4         credit_card                 18.78    NJ           RENT   

   Monthly.Income FICO.Range  Open.CREDIT.Lines  Revolving.CREDIT.Balance  \
0         6541.67    735-739               14.0                   14272.0   
1         4583.33    715-719               12.0                   11140.0   
2        11500.00    690-694               14.0                   21977.0   
3         3833.33    695-699               10.0                    9346.0   
4         3195.00    695-699               11.0                   14469.0   

   Inquiries.in.the.Last.6.Months Employment.Length  
0                             2.0          < 1 year  
1                             1.0           2 years  
2                             1.0           2 years  
3                             0.0           5 years  
4                             0.0           9 years

In [16]:
loans["Home.Ownership"].unique()

array(['MORTGAGE', 'RENT', 'OWN', 'OTHER'], dtype=object)

In [6]:
loans.dtypes

Amount.Requested                  float64
Amount.Funded.By.Investors        float64
Interest.Rate                     float64
Loan.Length                       float64
Loan.Purpose                       object
Debt.To.Income.Ratio              float64
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                 float64
Revolving.CREDIT.Balance          float64
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
dtype: object

# BUSINESS PROBLEM 2

In [5]:
price = pd.read_csv("Price_Quotes.csv")

In [6]:
price.head()

Order_Number  Barry_Price  Mary_Price
0             1          126         114
1             2          110         118
2             3          138         114
3             4          142         111
4             5          146         129

# BUSINESS PROBLEM: We would like to assess if there is any difference in the average price quotes provided by Mary and Barry

In [13]:
from scipy import stats

mary_prices = price['Mary_Price']
barry_prices = price['Barry_Price']

t_stat, p_value = stats.ttest_ind(mary_prices, barry_prices)

print('t-stat:', t_stat, 'p_value:', p_value)

t-stat: -1.4147436739281787 p_value: 0.17114226132118285


# BUSINESS PROBLEM 3: 
Determine what effect, if any, the reengineering effort had on the incidence behavioral problems and staff turnover. i.e To determine if the reengineering effort changed the critical incidence rate. Is there evidence that the critical incidence rate
improved?


In [4]:
facility = pd.read_csv("Treatment_Facility.csv")

In [5]:
facility.head()

Month Reengineer  Employee_Turnover       VAR4        VAR5
0      1      Prior             0.0000  24.390244   42.682927
1      2      Prior             6.0606  19.354839   25.806452
2      3      Prior            12.1212  35.087719  146.198830
3      4      Prior             3.3333  18.404908  110.429448
4      5      Prior            12.9032  17.964072   23.952096

In [6]:
# Separate the data into 'Before' and 'After' reengineering
before_reengineering = facility[facility['Reengineer'] == 'Prior']
after_reengineering = facility[facility['Reengineer'] == 'Post']

# Perform a t-test to compare the critical incident rates
# Assuming 'CI (%)' is the column representing the critical incident rate
critical_incident_before = before_reengineering['VAR5']
critical_incident_after = after_reengineering['VAR5']

# Perform a two-sample t-test
t_stat, p_value = stats.ttest_ind(critical_incident_before, critical_incident_after)

print('t-stat:', t_stat, 'p_value:', p_value)

t-stat: 1.627914425352865 p_value: 0.12091989189884148


# BUSINESS PROBLEM 4: 
We will focus on the prioritization system. If the system is working, then high priority jobs, on average, should be completed more quickly than medium priority jobs, and medium priority jobs should be completed more quickly than low priority jobs. Use the data provided to determine whether thisis, in fact, occurring.


In [7]:
priority = pd.read_csv("Priority_Assessment.csv")

In [9]:
# Group the data by priority levels
high_priority = priority[priority['Priority'] == 'High']['Days']
medium_priority = priority[priority['Priority'] == 'Medium']['Days']
low_priority = priority[priority['Priority'] == 'Low']['Days']

# Perform ANOVA test
f_statistic, p_value = stats.f_oneway(high_priority, medium_priority, low_priority)

print('t-stat:', t_stat, 'p_value:', p_value)

t-stat: 1.627914425352865 p_value: 0.16411459461716182


In [8]:
priority.head()

Days Priority
0   3.3     High
1   7.9   Medium
2   0.3     High
3   0.7   Medium
4   8.6   Medium

# BUSINESS PROBLEM 5: 
Use the survey results to address the following questions
 What is the overall level of customer satisfaction?
 What factors are linked to satisfaction?
 What is the demographic profile of Film on the Rocks patrons?
 In what media outlet(s) should the film series be advertised?

In [2]:
films = pd.read_csv("Films.csv")

# 1. Hypothesis Test for Overall Customer Satisfaction

In [5]:
import pandas as pd
from scipy.stats import ttest_ind, chi2_contingency
import statsmodels.api as sm

satisfaction_data = films["Overall"]

# Perform a t-test to check if the average satisfaction is significantly different from a reference value
# For example, if 3 represents "Average/Fair" satisfaction, you can test if the average satisfaction is significantly different from this value
reference_value = 3
t_stat, p_value = ttest_ind(satisfaction_data, [reference_value] * len(satisfaction_data))

print('t-stat:', t_stat, 'p_value:', p_value)

if p_value < 0.05:
    print("The overall customer satisfaction is significantly different from the reference value.")
else:
    print("The overall customer satisfaction is not significantly different from the reference value.")

t-stat: nan p_value: nan
The overall customer satisfaction is not significantly different from the reference value.


C:\Users\bless\AppData\Local\Temp\ipykernel_8104\109782601.py:10: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  t_stat, p_value = ttest_ind(satisfaction_data, [reference_value] * len(satisfaction_data))


# 2. Factors Linked to Satisfaction

In [11]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
import statsmodels.api as sm

# Load your dataset
data = pd.read_csv("films.csv")  

# Handle missing values by imputing with the mean
data.fillna(data.mean(), inplace=True)

# Convert non-numeric columns to numeric using one-hot encoding
data = pd.get_dummies(data, columns=["Gender", "Marital_Status", "Hear_About"], prefix=["Gender", "Marital", "Hear"])

# Define predictors and response variable
X = data[["Gender_1", "Gender_2", "Marital_1", "Marital_2", "Age", "Income", "Hear_1", "Hear_2", "Hear_3", "Hear_4", "Hear_5"]]
X = sm.add_constant(X)  # Add a constant (intercept) term
y = data["Overall"]

# Fit the OLS model
model = sm.OLS(y, X).fit()
print(model.summary())
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                Overall   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     1.306
Date:                Wed, 01 Nov 2023   Prob (F-statistic):              0.219
Time:                        22:39:53   Log-Likelihood:                -336.66
No. Observations:                 330   AIC:                             697.3
Df Residuals:                     318   BIC:                             742.9
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3082      0.308      4.244      0.0

C:\Users\bless\AppData\Local\Temp\ipykernel_8104\1592304346.py:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.fillna(data.mean(), inplace=True)


In [9]:
films.dtypes

_rowstate_          int64
Movie              object
Gender             object
Marital_Status     object
Sinage            float64
Parking           float64
Clean             float64
Overall           float64
Age               float64
Income            float64
Hear_About         object
dtype: object

# 3 What is the demographic profile of Film on the Rocks patrons?

In [12]:
# Load your dataset
data = pd.read_csv("films.csv")  

# Create a contingency table for the chi-squared test
contingency_table = pd.crosstab(data["Gender"], data["Marital_Status"])

# Perform the chi-squared test
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared statistic:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies table:")
print(expected)

# Interpret the results
alpha = 0.05  # Set your significance level
if p < alpha:
    print("There is a significant association between Gender and Marital Status.")
else:
    print("There is no significant association between Gender and Marital Status.")

Chi-squared statistic: 346.9614281894771
P-value: 6.137384670436033e-67
Degrees of freedom: 12
Expected frequencies table:
[[2.73658537e+01 6.46829268e+01 3.73170732e+00 5.59756098e+00
  6.21951220e-01]
 [5.20487805e+01 1.23024390e+02 7.09756098e+00 1.06463415e+01
  1.18292683e+00]
 [5.09756098e+00 1.20487805e+01 6.95121951e-01 1.04268293e+00
  1.15853659e-01]
 [3.48780488e+00 8.24390244e+00 4.75609756e-01 7.13414634e-01
  7.92682927e-02]]
There is a significant association between Gender and Marital Status.


# 4 In what media outlet(s) should the film series be advertised?

In [13]:
# Load your dataset
data = pd.read_csv("films.csv")  

# Create a contingency table for the chi-squared test
contingency_table = pd.crosstab(data["Hear_About"], data["Gender"])

# Perform the chi-squared test
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Print the results
print("Chi-squared statistic:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies table:")
print(expected)

# Interpret the results
alpha = 0.05  # Set your significance level
if p < alpha:
    print("There is a significant association between media outlets and gender.")
else:
    print("There is no significant association between media outlets and gender.")

Chi-squared statistic: 56.58986837509495
P-value: 0.002334466843543831
Degrees of freedom: 30
Expected frequencies table:
[[6.87925697e+00 1.29411765e+01 1.29411765e+00 8.85448916e-01]
 [3.12693498e-01 5.88235294e-01 5.88235294e-02 4.02476780e-02]
 [3.75232198e+00 7.05882353e+00 7.05882353e-01 4.82972136e-01]
 [6.25386997e-01 1.17647059e+00 1.17647059e-01 8.04953560e-02]
 [4.37770898e+00 8.23529412e+00 8.23529412e-01 5.63467492e-01]
 [6.25386997e-01 1.17647059e+00 1.17647059e-01 8.04953560e-02]
 [3.12693498e-01 5.88235294e-01 5.88235294e-02 4.02476780e-02]
 [1.28204334e+01 2.41176471e+01 2.41176471e+00 1.65015480e+00]
 [3.12693498e-01 5.88235294e-01 5.88235294e-02 4.02476780e-02]
 [7.06687307e+01 1.32941176e+02 1.32941176e+01 9.09597523e+00]
 [3.12693498e-01 5.88235294e-01 5.88235294e-02 4.02476780e-02]]
There is a significant association between media outlets and gender.


In [3]:
films.head()

_rowstate_                    Movie  Gender Marital_Status  Sinage  \
0           0  Ferris Buellers Day Off  Female        Married     2.0   
1           0  Ferris Buellers Day Off  Female         Single     1.0   
2           0  Ferris Buellers Day Off    Male        Married     2.0   
3           0  Ferris Buellers Day Off  Female        Married     1.0   
4           0  Ferris Buellers Day Off  Female        Married     1.0   

   Parking  Clean  Overall  Age  Income Hear_About  
0      2.0    2.0      2.0  3.0     1.0          5  
1      1.0    1.0      1.0  2.0     1.0          5  
2      4.0    3.0      2.0  4.0     1.0          5  
3      3.0    2.0      2.0  4.0     1.0          5  
4      1.0    1.0      1.0  3.0     3.0          1